FROM golang:1.24

WORKDIR /app

# libvips 설치
RUN apt-get update && apt-get install -y \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

# Air 설치
RUN go install github.com/air-verse/air@v1.61.7

# 모듈 초기화
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]